FROM --platform=linux/amd64 python:3.10.10

WORKDIR /app
COPY . .
RUN pip3 install streamlit
# ==1.9.0
# -r requirements.txt
EXPOSE 8501
CMD ["sleep","3600"]
# ENTRYPOINT [ "streamlit", "run" ]
# CMD [ "steamlit_app.py", "--server.headless", "true", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false"]

# ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
# ENTRYPOINT [ "streamlit", "run", "app.py" ]
# CMD [ "app.py", "--server.headless", "true", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false"]