default:
  image: python:3.10.10

variables:
  IMAGE_NAME: predict_employee
  IMAGE_TAG: latest

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10.10
  # before_script:
  #   - pip install pytest
  #   - pip install pandas
  #   - pip install pandera
  #   - pip install pytest-steps
  #   - pip install hydra-core
  #   - pip install scikit-learn
  #   - pip install omegaconf
  #   - pip install patsy
  # script:
  #   - pytest training/test
  script:
    - python --version

# .run_build:
#   stage: build
#   script:
#     - echo "woohoo, tests pass" 

python:
  # extends: ['.run_build']
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
    - python:3.10.10
  # before_script:
  #   - python --version

  # image: python:3.10.10
  # before_script:
  #   - pip install -r requirements.txt
  script:
    - docker --version
    - python --version
    # - python training/src/main.py
    # - bentoml build application/src
    # - bentoml models list

# docker:
#   extends: ['.run_build']
#   image: docker:20.10.16
#   script:
#     - docker --version
#     - ls ~

# build:
#   stage: build
#   image: ubuntu
#   services:
#     - python:3.10.10
#     - docker:20.10.16-dind
#   # before_script:
#   #   - pip install -r requirements.txt
#   script:
#     - python --version
#     - python training/src/main.py
#     - bentoml build application/src
#     - bentoml models list
#     # - pwd
#     # - ls
#     # - ls ~
#     - docker --version
    # - bentoml containerize $IMAGE_NAME:$IMAGE_TAG --opt platform=linux/amd64
    # - docker tag $IMAGE_NAME:$IMAGE_TAG pycaret1vund.azurecr.io/predict_employee
    # - docker push pycaret1vund.azurecr.io/predict_employee


# build_image:
#   stage: build
#   image: docker:20.10.16
#   # variables:
#   before_script:
#     - pip install bentoml
#   #   - apt-get update
#   #   - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#   #   - pip install bentoml
#   script:
#     - bentoml build application/src
#     - bentoml containerize $IMAGE_NAME:$IMAGE_TAG --opt platform=linux/amd64
#     - docker tag $IMAGE_NAME:$IMAGE_TAG pycaret1vund.azurecr.io/predict_employee
#     - docker push pycaret1vund.azurecr.io/predict_employee




