variables:
  IMAGE_NAME: predict_employee
  IMAGE_TAG: latest

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10.10
  before_script:
    - pip install pytest
    - pip install pandas
    - pip install pandera
    - pip install pytest-steps
    - pip install hydra-core
    - pip install scikit-learn
    - pip install omegaconf
    - pip install patsy
  script:
    - pytest training/test

.run_build:
  stage: build
  before_script:
    - pip install bentoml
  script:
    - bentoml build application/src
    - bentoml containerize $IMAGE_NAME:$IMAGE_TAG --opt platform=linux/amd64
    - docker tag $IMAGE_NAME:$IMAGE_TAG pycaret1vund.azurecr.io/predict_employee
    - docker push pycaret1vund.azurecr.io/predict_employee

python:
  extends: ['.run_build']
  image: python:3.10.10

node:
  extends: ['.run_build']
  image: docker:20.10.16

# build_image:
#   stage: build
#   image: docker:20.10.16
#   # variables:
#   before_script:
#     - pip install bentoml
#   #   - apt-get update
#   #   - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#   #   - pip install bentoml
#   script:
#     - bentoml build application/src
#     - bentoml containerize $IMAGE_NAME:$IMAGE_TAG --opt platform=linux/amd64
#     - docker tag $IMAGE_NAME:$IMAGE_TAG pycaret1vund.azurecr.io/predict_employee
#     - docker push pycaret1vund.azurecr.io/predict_employee




